---
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*/
    - staging
    - trying

cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin

go:
  - 1.17.x

language: go

notifications:
  email:
    on_success: never

os:
  - linux
  - osx

sudo: required
